### ISSUE TITLE
phpMyAdmin autosubmit preference selects don't work

### ISSUE THREAD

**Issue by formerandroider** [phpmyadmin/phpmyadmin#13915]
### Steps to reproduce
1. When on the main page, attempt to change a select-based preference (such as theme or current server).

### Expected behaviour
The preference should change.

### Actual behaviour
Nothing appears to happen - the displayed page has the same state as before the different preference was selected.

### Server configuration
**Operating system**: CentOS 7
**Web server:** Nginx 1.13.8
**Database:** -
**PHP version:** 7.2.0
**phpMyAdmin version:** 4.7.7, has been happening for a few versions now

### Client configuration

**Browser:** Chrome & Safari, Multiple versions
**Operating system:** Mac OS 10.12 & 10.13

**Comment by ibennetch** [comment]
I tried with RELEASE_4_7_7 and wasn't able to reproduce this (with a Debian Linux server). Are you able to see cookies related to phpMyAdmin in your browser?

**Comment by liamwli** [comment]
@ibennetch the demo seems to work fine. phpMyAdmin is indeed setting cookies fine.

It might be relevant that I'm using config based auth for the MariaDB servers.

**Comment by nijel** [comment]
The theme selection was indeed buggy at some point, not sure if it is fully fixed for 4.7 branch, but should be fixed for good since 263722fef8f69a15976c4cf2849ccd99d2770417 in master.

**Comment by mauriciofauth** [comment]
I marked it as a bug, because I remember it happening to me, but I can no longer reproduce it in the master branch.

**Comment by nijel** [comment]
As mentioned before, it should be really fixed in master, but I'm not sure with QA_4_7. The problem is that theme setting is there happening in same request as is currently rendering the page and depending on session interactions with other request, the theme change might fail.

**Comment by liamwli** [comment]
It should be noted that this happens with the server selection as well as theme selection, in case it was missed.

Changing the server does work if I pass it as a GET parameter...

**Comment by williamdes** [comment]
Reminds me of #14295 fixed by #14354

**Comment by williamdes** [comment]
@formerandroider Can you confirm that you still have this issue ?

**Comment by formerandroider** [comment]
Ah, no. I think it was a strange nginx configuration issue. I can’t remember which one, though.
