### ISSUE TITLE
Unable to log in with MySQL 8.0.11; caching_sha2_password authentication method unknown to the client 

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14220]
With MySQL 8.0.11 I'm unable to log in with users that had been working fine under previous versions (at least 8.0.0, perhaps even more recent than that).

> mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]
> 
> mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client

See also https://dev.mysql.com/doc/refman/8.0/en/authentication-plugins.html

I'm using QA_4_8.

**Comment by ibennetch** [comment]
See also https://stackoverflow.com/questions/49948350/phpmyadmin-on-mysql-8-0

**Comment by ibennetch** [comment]
Possibly related: https://github.com/phpmyadmin/phpmyadmin/issues/14217

**Comment by ibennetch** [comment]
A point release seems like a bad time to make changes to the authentication protocols. I've been testing with 8.0.4-rc which works fine, and now that 8.0.11 is out it causes problems.

**Comment by Gemorroj** [comment]
https://bugs.php.net/bug.php?id=76243

**Comment by yoho2021** [comment]
I met this issue a few days before, is there anyone who solve this problem?  thanks a lot~

**Comment by mauriciofauth** [comment]
There is not much we can do about it right now, as apparently PHP still does not support the `caching_sha2_password` authentication method.

However, I was able to connect successfully using other authentication methods such as `mysql_native_password` and `sha256_password`.

**Comment by szabacsik** [comment]
[https://stackoverflow.com/questions/49948350/phpmyadmin-on-mysql-8-0/50437307#50437307](https://stackoverflow.com/questions/49948350/phpmyadmin-on-mysql-8-0/50437307#50437307)

**Comment by rmanibus** [comment]
Upgrading to PHP7.2.7 solved the issue for me.

**Comment by donpaul120** [comment]
@rmanibus  i have php 7.2.7 and mysql  Ver 8.0.11 but im wondering why it doesn't work still.

**Comment by superlbr** [comment]
fail in php 7.2.8 and mysql  Ver 8.0.12

**Comment by Apollo725** [comment]
I expired root user and reinstall all of the mysql workspace, then I got this error.
Warning: mysqli_connect(): The server requested authentication method unknown to the client [caching_sha2_password] in /Volumes/Workspace/workspace/test/php_test/Simple-PHP-Login/add.php on line 3

I was using mac and didn't use xampp.

**Comment by hkrware** [comment]
php-fpm 7.2.11 and mysql 8.0.12 both on centos 7.5.1804 x64 and not working

**Comment by mauriciofauth** [comment]
As mentioned earlier, there is not much we can do about it at this time.
The [_mysqlnd_](https://secure.php.net/manual/en/intro.mysqlnd.php) library [does not support](https://bugs.php.net/bug.php?id=76243) the [`caching_sha2_password`](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html) authentication method yet.
An [alternative](https://secure.php.net/manual/en/mysqlinfo.library.choosing.php) would be to use the [_libmysqlclient_](https://dev.mysql.com/downloads/connector/c/) library, however PHP [does not support](https://bugs.php.net/bug.php?id=76282) the _libmysqlclient_ library of MySQL 8 yet.

So the real alternative, for now, is to [use another authentication method](https://dev.mysql.com/doc/refman/8.0/en/authentication-plugins.html) other than `caching_sha2_password`.

**Comment by SugarD-x** [comment]
I'm not sure if this helps anything, but on MySQL Server 8.0.12, I'm getting this error ONLY when upgrading to PHP 7.2.11. (It doesn't just affect PHPMyAdmin). When I revert back to PHP 7.2.8, I have no problems. Seems a bit odd that a _newer_ version of PHP would cause this.

I know downgrading PHP is probably not the greatest idea, but if this helps anyone as a temporary solution, it is there.

**Comment by mauriciofauth** [comment]
@SugarD-x This is related to commit https://github.com/php/php-src/commit/d6e81f0bfd0cb90586dd83d4fd47a4302605261a which was later reverted by https://github.com/php/php-src/commit/03740ef7dffcc80530a89ebde3ccf5464f7f18e6.

**Comment by SugarD-x** [comment]
@mauriciofauth Thank you! That definitely explains my issue.

**Comment by doveraudio** [comment]
I used this to get it back when I started a new dev server with mysql 8 and php 7.3 
` ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY 'PASSWORD'; `

it seems to be working ok so far.

**Comment by SugarD-x** [comment]
@doveraudio That is the workaround, not an actual fix. That just updates your root database login to use the old password authentication method, rather than this new one.

**Comment by p8ul** [comment]
I was able to connect successfully using other authentication methods such as `mysql_native_password`
By running this command on mysql on the terminal. 
` cd /usr/local/mysql/bin `
`./mysql -u root -p`
Run command below on msql terminal
`CREATE USER sky@localhost IDENTIFIED WITH mysql_native_password BY 'password'`

**Comment by bigwavealex** [comment]
doveraudio's suggestion worked for me as well.   I'm using php7.3, caching_sha2 still not working there either I guess, hopefully they are working on it.

**Comment by smumargilani** [comment]
> https://stackoverflow.com/questions/49948350/phpmyadmin-on-mysql-8-0
> 
> I was able to connect successfully using other authentication methods such as `mysql_native_password`
> By running this command on mysql on the terminal.
> `cd /usr/local/mysql/bin`
> `./mysql -u root -p`
> Run command below on msql terminal
> `CREATE USER sky@localhost IDENTIFIED WITH mysql_native_password BY 'password'`

Works for me as well, thanks @p8ul

**Comment by mauriciofauth** [comment]
The `caching_sha2_password` authentication method will only be supported in PHP 7.4+ due to the hard dependency on ext/hash. See https://github.com/php/php-src/commit/4f06e67ad2201390ed35a9ea6288a00c0b04782b.

**Comment by antonioaltamura** [comment]
The built-in PHP version in MacOS mojave is PHP 7.1.23 (I installed mysql  Ver 8.0.15 )
So what's the current preferred way to run phpMyAdmin?

**Comment by SugarD-x** [comment]
You'll have to use the workaround for mysql_native_password in the mean time.

**Comment by vladyslavstartsev** [comment]
> The built-in PHP version in MacOS mojave is PHP 7.1.23 (I installed mysql Ver 8.0.15 )
> So what's the current preferred way to run phpMyAdmin?

@antonioaltamura you can run phpmyadmin on MacOS via Docker

**Comment by vipankumar-JFL** [comment]
mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpassword';


login through command line, it works after that

**Comment by SugarD-x** [comment]
> mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'rootpassword';
> 
> login through command line, it works after that
That is only a workaround, and has been said on here a few times now. It is not an actual fix to the issue.

**Comment by florian2833z** [comment]
Has this been fixed?

**Comment by SugarD-x** [comment]
> Has this been fixed?
From my understanding, it is waiting on PHP 7.4.0 to be released, as it is an issue on their end.

**Comment by mauriciofauth** [comment]
A note from the [PHP documentation](https://www.php.net/manual/en/mysqli.requirements.php):

>  When running a PHP version before 7.1.16, or PHP 7.2 before 7.2.4, set MySQL 8 Server's   default password plugin to _mysql_native_password_ or else you will see errors similar to _The server requested authentication method unknown to the client [caching_sha2_password]_ even when _caching_sha2_password_ is not used.
> 
> This is because MySQL 8 defaults to caching_sha2_password, a plugin that is not recognized by the older PHP (mysqlnd) releases. Instead, change it by setting _default_authentication_plugin=mysql_native_password_ in `my.cnf`. The _caching_sha2_password_ plugin will be supported in a future PHP release. In the meantime, the [mysql_xdevapi](https://www.php.net/manual/en/book.mysql-xdevapi.php) extension does support it.

**Comment by xz0tic** [comment]
im trying to login phpmyadmin with xampp for the first time and i keep getting this:
https://imgur.com/CmxPcSR

 Cannot log in to the MySQL server

mysqli_real_connect(): The server requested authentication method unknown to the client [sha256_password]
 mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client
 Connection for controluser as defined in your configuration failed.
 mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]
 mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client

**Comment by OGJAYYOU** [comment]
mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]
mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client
Connection for controluser as defined in your configuration failed.
mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]
mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client

**Comment by OGJAYYOU** [comment]
i changed the method to mysql_native_password and it worked then i also checked config.db.php and renewed the old variables(username and password).

**Comment by SugarD-x** [comment]
That is still a temporary workaround, not a long-term solution. Once the appropriate version of PHP comes out that resolves this problem, it won't be an issue anymore.

**Comment by yanickrochon** [comment]
I do not understand this issue. My app can connect just fine to MySQL 8 using `caching_sha2_password`, and so does phpMyAdmin to perform queries, etc. Yet, this annoying block of errors pops up :

![image](https://user-images.githubusercontent.com/78461/69246348-91e56d80-0b76-11ea-8fa1-326cc2b11007.png)

Both the `pma` and my app's credential use the `mysql_native_password` method, and my app connects just fine.

I don't get it.

**Comment by ibennetch** [comment]
I believe this has been resolved with the release of PHP 7.4; affected users will need to upgrade their PHP installations to take advantage of the upgraded support in the PHP library.

I think we should close this issue now that PHP 7.4 is available.

**Comment by ibennetch** [comment]
@yanickrochon It's odd to me that you'd see the same message repeated so many times. I suggest clearing your phpMyAdmin cookies (they start with 'pma_') or trying with private browsing mode; you can also try with a minimal `config.inc.php` file and see if that improves the situation. You could try logging in directly as the pma user, to make sure that part works correctly as well.

**Comment by wildone** [comment]
docker container still on 7.2 :(

**Comment by ibennetch** [comment]
Max, I’m glad you mentioned that. I noticed it earlier today and plan to upload a fix soon. See https://github.com/phpmyadmin/docker/issues/258 to monitor the issue.

**Comment by SugarD-x** [comment]
From what I'm hearing from multiple sources, this was fixed in PHP 7.4.0, however after upgrading, I'm getting the caching_sha2_password issues again. I'm at a loss as to why PHP and MySQL refuse to communicate through this authentication method, even in a version that supposedly supports it. I can't even get into PHPMyAdmin to see what is going on either. It works fine in PHP 7.2.8, (the last one to support it until 7.4.0).

I'm beginning to think this isn't actually fixed like PHP claims.

**Comment by ibennetch** [comment]
SugarD-x, could you send us a list of your exact PHP, MySQL, and phpMyAdmin versions - or screenshot from the home page that shows that information (obscuring anything sensitive like the server hostname)?

**Comment by SugarD-x** [comment]
PHP: 7.4.0
MySQL: Community Server 8.0.18
PHPMyAdmin: 4.9.2

They are all the latest production versions as of this posting. I upgraded everything except PHP and it was still working fine. (I was on PHP 7.2.8 prior to this issue, which was the last version before PHP 7.4.0 to support caching_sha2_password). As soon as I updated PHP, the issues popped up.

I've literally spent hours trying to hunt down the cause to no avail.

**Comment by SugarD-x** [comment]
Looks like I finally got an answer. It is **not** officially "fully" supported as of PHP 7.4.0 yet. Looks like I'll have to revert back to PHP 7.2.8 until the next release.

https://github.com/php/php-src/commit/4f06e67ad2201390ed35a9ea6288a00c0b04782b#commitcomment-36398518

**Comment by SugarD-x** [comment]
Just a quick heads up for everyone, this was **not** fixed in PHP 7.4.1, as originally planned. I'm still waiting for them to update the tag on the issue too. (They haven't created one for PHP 7.4.2 yet, and PHP 7.4.1 hasn't been listed as released online on the main website either. It is only available on the Windows PHP one right now).

**Comment by cplaiu** [comment]
PHP 5.4.16
MySQL: Community Server 8.0.18
PHPMyAdmin: 4.4.15.10
Centos: 7


I added default-authentication-plugin=mysql_native_password to the file /etc/my.cfg and use ALTER USER root IDENTIFIED WITH mysql_native_password BY 'PASSWORD'; but still not work.

![image](https://user-images.githubusercontent.com/32199465/71090868-41c4ef80-21a4-11ea-9353-e32c080f4eb9.png)

**Comment by SugarD-x** [comment]
You need to change "PASSWORD" to the password you want. You just changed your root password literally to "PASSWORD" without the quotes if you used that command as is.

**Comment by ibennetch** [comment]
cplaiu That is a generic error message that doesn’t apply to this specific
solution. Are you sure the MySQL server process is running? Can you connect
from the command line client? Perhaps try changing between host “localhost”
and “127.0.0.1” in config.inc.php (in case your user has access through one
connection type but not the other).

**Comment by cplaiu** [comment]
> You need to change "PASSWORD" to the password you want. You just changed your root password literally to "PASSWORD" without the quotes if you used that command as is.

It's what I do.

ALTER USER root@'localhost' IDENTIFIED WITH mysql_native_password BY 'mypassword';

> cplaiu That is a generic error message that doesn’t apply to this specific solution. Are you sure the MySQL server process is running? Can you connect from the command line client? Perhaps try changing between host “localhost” and “127.0.0.1” in config.inc.php (in case your user has access through one connection type but not the other).

Yes I'm sure that mysql process is running, because I can connect from the CLI. I try to change “localhost” to 127.0.0.1”.

netstat -atnlp|grep -i "3306\|mysql" returns:

tcp6       0      0 :::33060                :::*                    LISTEN      27697/mysqld
tcp6       0      0 :::3306                 :::*                    LISTEN      27697/mysqld

I try to bind-address=0.0.0.0 in /etc/my.cfg

**Comment by ibennetch** [comment]
We've added a FAQ about this (1ae14b59a40ff5d8b62b50f9c1172dbea0e61b1f), and since this isn't a bug with phpMyAdmin I'm going to suggest we close this issue.
