### ISSUE TITLE
[IIS] Failed to store CSRF token in session! 

### ISSUE THREAD

**Issue by fraria76** [phpmyadmin/phpmyadmin#15267]
Hi everyone,

I state that I am a newbie and I have this configuration just installed:

- Windows Server 2019 with IIS 10
- Prestashop 1.7.5.2
- MySql 5.6.16.0
- PhpMyAdmin 4.8.5
- PHP 7.2.18

If I type localhost/install the PrestaShop installation starts and I reach the point where I have to create a database, but when I go to type localhost/phpmyadmin
the error appears:

phpMyAdmin - error
Failed to store CSRF token in session! Probably sessions are not working properly

If I query phpmyadmin with a "mysqltest.php" file by typing localhost/phpmyadimn/mysqltest.php ,appears:

Connected to MySQL successfully
Database selected successfully

Can you please give me advice to solve?

Thank you very much for any helps!

**Comment by fraria76** [comment]
Hi everyone,
I solved with install PHPMyAdmin 4.1.9 instead of 4.8.5.
In doing so, I access http://localhost/phpmyadmin/
Kind regards

**Comment by williamdes** [comment]
@fraria76 Can you please download on our [website](https://www.phpmyadmin.net/downloads/) the latest version in development [(phpMyAdmin 4.8+snapshot)](https://www.phpmyadmin.net/downloads/) and tell us if the issue still exists ?

**Comment by williamdes** [comment]
I am trying to reproduce the issue

How to install WS2019
- Article: https://medium.com/@RealNetwork/direct-download-links-windows-server-2019-datacenter-standard-essentials-hyper-v-server-2019-5f53357eeeac
- Product keys: https://www.windows8facile.fr/telecharger-windows-server-2019/

**Comment by williamdes** [comment]
@fraria76 are you talking about "Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin." ?

**Comment by williamdes** [comment]
I had to allow write access to the webserver (or php ?) to the folder `C:/Windows/Temp`
But that did not solve the issue, there is still an issue with session IDS

`set_session` is sent and used but the browser still sends different session ids, a complex issue...

**Comment by fraria76** [comment]
> Can you please download on our [website](https://www.phpmyadmin.net/downloads/) the latest version in development [(phpMyAdmin 4.8+snapshot)](https://www.phpmyadmin.net/downloads/) and tell us if the issue still exists ?

Hello williamdes,
as soon as possible I will take the required test and then update you
Kind regards

**Comment by fraria76** [comment]
Hello williamdes,

I think I found a solution by reading this blog https://www.ostraining.com/blog/coding/update-phpmyadmin/

- Rename phpMyAdmin folder to phpMyAdmin_old
- Create new phpMyAdmin folder
- Copy phpMyAdmin Configuration File “config.inc.php”(from phpMyAdmin_old) into new phpMyAdmin directory
- Download the 4.8.5 version of phpMyAdmin and extract the files into new phpMyAdmin directory
- into C:\inetpub\wwwroot\phpmyadmin create tmp folder and give user USER full control
- into config.inc.php file go to insert	$cfg['tempdir'] = '/tmp';      
 
   $cfg['UploadDir'] = '';
   $cfg['SaveDir'] = '';
   **$cfg['tempdir'] = '/tmp';**

Kind regards

**Comment by williamdes** [comment]
@fraria76 I think this issue can be closed if it is solved ?

**Comment by fraria76** [comment]
Hi,
yes it's solved.
Kind regards

**Comment by WangWenBin2017** [comment]
Hi, I solved the problem. My environment is exactly the same as the subject's problem.
Just add the IUSR user to the Windows \ Temp directory and grant all permissions.

**Comment by I-Info** [comment]
> Hi, I solved the problem. My environment is exactly the same as the subject's problem.
> Just add the IUSR user to the Windows \ Temp directory and grant all permissions.

Not entirely correct, I added permissions to the USERS group.And it worked.It is no use to add IUSR to it on my computer.

**Comment by I-Info** [comment]
But your advice is helpful
