### ISSUE TITLE
Dragging in Designer is inconsistent and frustrating

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#16199]
### Describe the bug

When using Designer, I drag the tables around. Sometimes, the table gets "stuck" at what seems like a boundary area; for instance in this screenshot, "rental" is as far up and to the right as I can easily make it go:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/1443710/84795057-04131900-afc5-11ea-85fd-9f9530b5b7f3.png">

A symptom of the problem is that the item stays selected and drags around through the window even when my mouse button isn't clicked; so in this case I clicked and dragged on the "rental" window, it got "stuck" in the upper right, then I let go of the mouse, and it still drags around with my cursor movement. Once a window is "captured" in this way, rapid mouse movement usually leaves the window where it was and very slow movement drags the window along with the cursor.

Another symptom is that, when the dragging problem is occurring, the cursor movements select text (such as the tabs across the top, or the words in the pop out menu, or in extreme cases even the database names in the navigation pane). 

The problem is exacerbated by moving the mouse quickly while dragging, but isn't exclusively caused by that.

### To Reproduce

Go to Designer, try to drag a few windows around.

Move windows toward the upper third or right hand third of the available canvas.

Move windows rapidly.

### Server configuration

- Operating system: Debian
- Web server: Apache 
- Database version: MariaDB 10.3.22
- PHP version: 7.4.6
- phpMyAdmin version: QA_4_9, QA_5_0, master

### Client configuration

- Browser: Firefox 77, Chrome 83
- Operating system: MacOS

- Browser: Edge 44
- Operating system: Windows 10

**Comment by codyclearsky** [comment]
Hi, I found this frustrating also as I really like the designer and ability to add relations easily.

I have found a fix for this

in js/designer/move.js change the following

---Under DesignerMove.enablePageContentEvents = function () { ----

from line 1995 - 2001, change the $('#page_content').on to $(document).on

Sorted it right out for me :)

**Comment by shucon** [comment]
Fixed in upcoming PR: https://github.com/phpmyadmin/phpmyadmin/pull/16321, fix is similar to what @codyclearsky mentioned. Unfortunately, I saw it after I fixed it.

**Comment by amyequinn** [comment]
great thank you!

**Comment by overholted** [comment]
I'm having this issue as well. I tried the solution posted by codyclearsky, but it didn't work for me. Any other ideas? I'm on Windows 11 using Xampp and it occurs in Chrome, Edge and Vivaldi.

**Comment by liviuconcioiu** [comment]
> I'm having this issue as well. I tried the solution posted by codyclearsky, but it didn't work for me. Any other ideas? I'm on Windows 11 using Xampp and it occurs in Chrome, Edge and Vivaldi.

Probably because you've edited the wrong file. The correct one should be `js\dist\designer\move.js`. Notice the `dist` folder. `src` is if you want to push a commit on Github. Also, the lines won't match because there were several commits probably since then.

**Comment by overholted** [comment]
> > I'm having this issue as well. I tried the solution posted by codyclearsky, but it didn't work for me. Any other ideas? I'm on Windows 11 using Xampp and it occurs in Chrome, Edge and Vivaldi.
> 
> Probably because you've edited the wrong file. The correct one should be `js\dist\designer\move.js`. Notice the `dist` folder. `src` is if you want to push a commit on Github. Also, the lines won't match because there were several commits probably since then.

I thought perhaps you were on to something when I checked that directory only to find there was no move.js file there. I copied it there from my backup folder and edited as codycleasky suggested, restarted Apache and MySQL, but I'm still having the same issue.

**Comment by williamdes** [comment]
> I thought perhaps you were on to something when I checked that directory only to find there was no move.js file there. I copied it there from my backup folder and edited as codycleasky suggested, restarted Apache and MySQL, but I'm still having the same issue.

Please try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)

It should be fixed
