### ISSUE TITLE
PHP 8.0: Opening Structure tab fails

### ISSUE THREAD

**Issue by joostdebruijn** [phpmyadmin/phpmyadmin#16449]
### Describe the bug

Opening the Structure tab of a table fails with PHP 8.0-rc3 with the following error:

```
PHP message: PHP Fatal error:  Uncaught Error: Unknown named parameter $create_add_field in /var/www/html/phpmyadmin/vendor/symfony/dependency-injection/ContainerBuilder.php:1144
Stack trace:
#0 /var/www/html/phpmyadmin/vendor/symfony/dependency-injection/ContainerBuilder.php(1144): ReflectionClass->newInstanceArgs()
#1 /var/www/html/phpmyadmin/vendor/symfony/dependency-injection/ContainerBuilder.php(618): Symfony\Component\DependencyInjection\ContainerBuilder->createService()
#2 /var/www/html/phpmyadmin/vendor/symfony/dependency-injection/ContainerBuilder.php(558): Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#3 /var/www/html/phpmyadmin/tbl_structure.php(68): Symfony\Component\DependencyInjection\ContainerBuilder->get()
#4 {main}
  thrown in /var/www/html/phpmyadmin/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1144
```

### To Reproduce

1. Go to a database
2. Select a table
3. Select the Structure tab -> results in: Error in processing request Error code: 500

### Expected behavior

The tab should open and show the table structure.

### Screenshots
n/a

### Server configuration

- Operating system: Ubuntu 20.04.1
- Web server: nginx
- Database version: MariaDB 10.5.6
- PHP version: 8.0.0-rc.3
- phpMyAdmin version: 5.0.4

### Client configuration

- Browser: Chrome 86.0.4240.111
- Operating system: Windows 10.0.19042.610

### Additional context
n/a

**Comment by williamdes** [comment]
Duplicate of #16301

**Comment by williamdes** [comment]
Hi @joostdebruijn 
Are you sure you did unzip correctly 5.0.4 ?
Because from what I see on https://github.com/code-lts/phpmyadmin-releases/blame/upstream/version/source/5.0.3/vendor/symfony/dependency-injection/ContainerBuilder.php#L1144 that should be fixed.
Upstream: https://github.com/symfony/symfony/issues/38089

**Comment by joostdebruijn** [comment]
Hi @williamdes,
Thanks for the quick reply! I did not ran composer install after upgrading to 5.0.4. It works correctly now. 😄

**Comment by tonydream888** [comment]
I am using the phpMyAdmin version 5.0.4 but the problem still exist. I just moved to a new server (CentOS 7, PHP 8, Vesta Panel), the current Symfony installed is version 4

**Comment by williamdes** [comment]
Could you check the file I mentioned is exactly the same ? https://github.com/phpmyadmin/phpmyadmin/issues/16449#issuecomment-720461096

**Comment by tonydream888** [comment]
Should be different, because the total lines of the one on my server is 1594, but yours is 1672

**Comment by tonydream888** [comment]
if you need I can upload the file(/usr/share/php/Symfony4/Component/DependencyInjection/ContainerBuilder.php) for you

**Comment by tonydream888** [comment]
The phpMyAdmin on my server is installed by the Vesta Control Panel, not sure if that is the reason

**Comment by williamdes** [comment]
Ah, you are using a Debian installed phpMyAdmin ?

**Comment by tonydream888** [comment]
No, my server is CentOS 7

**Comment by williamdes** [comment]
> No, my server is CentOS 7

Okay, maybe a packaging issue
cc @remicollet 
https://centos.pkgs.org/8/remi-x86_64/phpMyAdmin-5.0.4-1.el8.remi.noarch.rpm.html

The package depends on
`(php-composer(symfony/dependency-injection) | >= 4.2.8 with php-composer(symfony/dependency-injection) < 5)`

**Comment by tonydream888** [comment]
So what should I do in my case? Download and install phpMyAdmin-5.0.4-1.el8.remi.noarch.rpm ?

**Comment by williamdes** [comment]
Installing https://centos.pkgs.org/8/remi-x86_64/php-symfony4-dependency-injection-4.4.16-1.el8.remi.noarch.rpm.html should fix this issue :crossed_fingers:

**Comment by remicollet** [comment]
@williamdes no, this package is for CentOS 8.

**Comment by williamdes** [comment]
Oh okay
Any version in ` 5.x (#38091)  v5.2.0  v5.2.0-RC2 v5.2.0-RC1 v5.2.0-BETA3 v5.2.0-BETA2 v5.2.0-BETA1 v5.1.9 v5.1.8 v5.1.7 v5.1.6 v4.4.17 v4.4.16 v4.4.15 v4.4.14 v3.4.47 v3.4.46 v3.4.45` (source: https://github.com/symfony/symfony/commit/8e34978e4e2c4bf7dac97e44e904368c4cfb54f8)
Should fix the issue

**Comment by tonydream888** [comment]
Just tried to install the rpm but got the following errors

warning: php-symfony4-dependency-injection-4.4.16-1.el8.remi.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 5f11735a: NOKEY
error: Failed dependencies:
        (php-composer(psr/container) >= 1.0 with php-composer(psr/container) < 2.0) is needed by php-symfony4-dependency-injection-4.4.16-1.el8.remi.noarch
        (php-composer(symfony/service-contracts) >= 1.1.10 with php-composer(symfony/service-contracts) < 2) is needed by php-symfony4-dependency-injection-4.4.16-1.el8.remi.noarch
        php-symfony4-common = 4.4.16-1.el8.remi is needed by php-symfony4-dependency-injection-4.4.16-1.el8.remi.noarch
        rpmlib(RichDependencies) <= 4.12.0-1 is needed by php-symfony4-dependency-injection-4.4.16-1.el8.remi.noarch

**Comment by tonydream888** [comment]
Is it possible I just install another copy of phpMyAdmin?

**Comment by tonydream888** [comment]
Thank you very much, I directly modified the PHP file by following https://github.com/symfony/symfony/commit/8e34978e4e2c4bf7dac97e44e904368c4cfb54f8

It seems working now, thank you very much!

**Comment by cdxcorydavis** [comment]
Ok, so im new to linux, this exact situation happened to me, this thread fixed my problem but i have to know how this happened?! what did i do to cause this?

**Comment by williamdes** [comment]
> Ok, so im new to linux, this exact situation happened to me, this thread fixed my problem but i have to know how this happened?! what did i do to cause this?

Just a Symfony bug :/

**Comment by amira-98** [comment]
> 
> 
> Ah, you are using a Debian installed phpMyAdmin ?

I am using debian with phpmyadmin 5.0.4 and still having the same problem :/

**Comment by williamdes** [comment]
> > Ah, you are using a Debian installed phpMyAdmin ?
> 
> I am using debian with phpmyadmin 5.0.4 and still having the same problem :/

Hi @amira-98 
You should install the latest version from our [website](https://www.phpmyadmin.net/downloads/) :)
