### ISSUE TITLE
Error in processing request. Error Text Error (rejected). It seems like connectivity to the server has been lost. Please check your connectivity and server status. 

### ISSUE THREAD

**Issue by kingx619** [phpmyadmin/phpmyadmin#16545]
### Describe the bug
I keep getting this error all the time Error in processing request. Error Text Error (rejected). It seems like connectivity to the server has been lost. Please check your connectivity and server status. 

I have done everything mentioned on the stack overflow changing localhost to 127.0.0.1 but still the situation remains the same

### To Reproduce

2. Click on '....' Databases in php my admin

### Expected behavior
I have not changed anything or any setting in phpmyadmin or my sql . Till now I never got this bug. 

### Server configuration

- Operating system:
- Web server: Laragon with apache 2.4.46
- Database version: 8.0.22  MySQL Community Server - GPL
- PHP version: 8.0.0
- phpMyAdmin version: 5.0.4

### Client configuration

- Browser:  Version 87.0.4280.88 (Official Build) (64-bit)
![A](https://user-images.githubusercontent.com/75287291/102876001-9c092800-446a-11eb-95ca-2085c45b0c1a.PNG)

- Operating system: Windows 10 x 64 build 19042.685 20H2

**Comment by williamdes** [comment]
Hi,
What was the issue that made the error?

**Comment by gzuaps** [comment]
I'm also seeing this issue.
Was any fix identified.

**Comment by williamdes** [comment]
> I'm also seeing this issue.
> I generally see it when I switch between servers in the dropdown list, but the connection to the "new" server is still made.
> phpMyAdmin-5.0.4-1.el8.remi.noarch
> php-fpm-7.4.15-1.el8.remi.x86_64
> It's more irritating than a real issue.
> Was any fix identified.

Are you saying you can not login on 2 servers at a time?

Could you describe more the issue please?

**Comment by swamyuma** [comment]
I am seeing this issue as well.

phpMyAdmin:  5.0.4 

Is there any update on this?
It was working fine until this week when I started seeing this message all of a sudden!

**Comment by gzuaps** [comment]
As stated, but with more information.
I am connected to server1, it is shown in the "current server:" field, I can see a list of the DBs on server1.
I dropdown the current server list and choose server2,  I see the error but the connection continues to be made,
I can then see the list of DBs on server2.
As stated it is more of an irritation than a real issue.

**Comment by williamdes** [comment]
> As stated it is more of an irritation than a real issue.

I understand, let's find a fix

> I can then see the list of DBs on server2.

Are you switching servers when the first loading did not end ?

If anyone can reproduce this on a demo server (`root`, no password) that would help a lot and allow us to fix this issue
- [`5.2.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.1.x-dev`](https://demo.phpmyadmin.net/QA_5_1/)
- [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by gzuaps** [comment]
I still see the error even if I wait approx 10 secs after the loading ends.
It appears random i.e. it doesn't happen every time.

**Comment by williamdes** [comment]
> I still see the error even if I wait approx 10 secs after the loading ends.
> It appears random i.e. it doesn't happen every time.

On demo servers ?

Could you open the developer console and let me know what request fails ?

**Comment by gzuaps** [comment]
AFAIKS switching servers does not produce output in the console, only SQL queries.

**Comment by williamdes** [comment]
> AFAIKS switching servers does not produce output in the console, only SQL queries.

It produces network requests, and I am curious to know what is that request that fails

**Comment by gzuaps** [comment]
There is nothing in the console when I switch servers, I only see the red error message as originally reported by kingx619.

**Comment by williamdes** [comment]
> There is nothing in the console when I switch servers, I only see the red error message as originally reported by kingx619.

I maybe understand, do you mean you switched servers and afterwards another browser tab throws the error ?

A step by step procedure to follow would help me because I have no way te reproduce this issue currently but I use multi servers every day without any error
Screenshots or a gif can help too

**Comment by gzuaps** [comment]
Thanks for bringing up the subject of browsers, it looks like it is browser dependent.
Same errors in Firefox on Linux and Windows 10.
No error in Chrome and Falkon on Linux, and Edge in Windows 10.

**Comment by kingx619** [comment]
I have searched a lot of this and realized that this error occurred when I edited something in my php.ini file.  My sql community edition 8.0.23 is out now along with php version 8.0.2 . I use Laragon which is possibly the best PHP development Environment just like XAMPP, or WAMP. I just removed all my previous phpmyadmin files and updated the php version to 8.0.2 and mysql version to 8.0.23 which removed all kinds of errors including the Error Error text rejected.  This error also has some kind of relation with config.inc.php file present inside php my admin installation.  So make sure you unzip the fresh phpmyadmin installation (version 5.0.4) and the replace the existing one on your server after updating PHP and mysql.

**Comment by khatchad** [comment]
I use the same browser and same OS on two machines at two different locations. One never has the problem, the other constantly has it. I also tried a different browser on the problematic machine with the same result. To produce this error, all I need to do is enter a custom query. The "search" feature works fine.

**Comment by williamdes** [comment]
> I use the same browser and same OS on two machines at two different locations. One never has the problem, the other constantly has it. I also tried a different browser on the problematic machine with the same result. To produce this error, all I need to do is enter a custom query. The "search" feature works fine.

Hi @khatchad 
This is quite strange, do you have any extensions enabled ?

**Comment by khatchad** [comment]
> > I use the same browser and same OS on two machines at two different locations. One never has the problem, the other constantly has it. I also tried a different browser on the problematic machine with the same result. To produce this error, all I need to do is enter a custom query. The "search" feature works fine.
> 
> Hi @khatchad 
> This is quite strange, do you have any extensions enabled ?

Do you mean chrome extensions? Firefox extensions? If so, yes.

**Comment by williamdes** [comment]
> > > I use the same browser and same OS on two machines at two different locations. One never has the problem, the other constantly has it. I also tried a different browser on the problematic machine with the same result. To produce this error, all I need to do is enter a custom query. The "search" feature works fine.
> > 
> > 
> > Hi @khatchad
> > This is quite strange, do you have any extensions enabled ?
> 
> Do you mean chrome extensions? Firefox extensions? If so, yes.

Yes, did you try to use private/incognito browsing mode

Maybe you have an antivirus ?

Could you check your developer console to find out about what the server answers ?

**Comment by khatchad** [comment]
Yup, tried incognito browsing mode. I got the same result. I'm on Ubuntu; no antivirus. I'll check the dev console.

**Comment by khatchad** [comment]
I'm seeing this in the console when I try to issue a query:
```
jquery.min.js?v=5.0.4:2 POST http://54.221.168.95/phpMyAdmin/import.php net::ERR_CONNECTION_RESET
send @ jquery.min.js?v=5.0.4:2
ajax @ jquery.min.js?v=5.0.4:2
jQuery.ajax @ jquery-migrate.js?v=5.0.4:257
k.<computed> @ jquery.min.js?v=5.0.4:2
(anonymous) @ sql.js?v=5.0.4:560
newFunc @ error_report.js?v=5.0.4:267
dispatch @ jquery.min.js?v=5.0.4:2
$event.dispatch @ jquery.event.drag-2.2.js?v=5.0.4:374
v.handle @ jquery.min.js?v=5.0.4:2
```

**Comment by khatchad** [comment]
Server: ... via TCP/IP
Server type: MySQL
Server connection: SSL is not being used
Server version: 8.0.20 - Source distribution
Protocol version: 10
Server charset: UTF-8 Unicode (utf8mb4)
Apache/2.4.41 (Ubuntu)
Database client version: libmysql - mysqlnd 7.4.3
PHP extension: mysqli mbstring
PHP version: 7.4.3
Version information: 5.0.4, latest stable version: 5.1.0

**Comment by khatchad** [comment]
OK, this is strange. I issued an `apt upgrade` and rebooted. Now, I am not getting the error.

**Comment by williamdes** [comment]
> OK, this is strange. I issued an `apt upgrade` and rebooted. Now, I am not getting the error.

Maybe did you upgrade phpMyAdmin ?
Glad to know this is fixed

**Comment by khatchad** [comment]
No, I did not upgrade phpMyAdmin.

**Comment by jeongpark29** [comment]
I have found the solution.

https://github.com/symfony/symfony/commit/8e34978e4e2c4bf7dac97e44e904368c4cfb54f8

**Comment by sadeghipour** [comment]
problem still remain on 5.1.3 but I down graded to 4.9.10 and get same error again
Server type: MySQL
Server version: 8.0.27-0ubuntu0.21.04.1 - (Ubuntu)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8mb4)

Apache/2.4.46 (Ubuntu)
Database client version: libmysql - mysqlnd 7.4.16
PHP extension: mysqliDocumentation
PHP version: 7.4.16

phpMyAdmin
Version information: 4.9.10

**Comment by williamdes** [comment]
> Is this piece of crap even being maintained?

What are you talking about?

**Comment by michacassola** [comment]
I also have this problem, was this fixed and I have too keep on checking where the error might come from?
I install the latest PMA with composer and symlink it, so it is accessible from a subfolder of a website (/pma/). I use the latest PHP 8.0 and the latest mainline NGINX (1.21.6). It used to work recently (few weeks ago) but now it doesn't.
Any help fixing this will be appreciated in contrast to troll stuff seen above. Thanks in advance!

**Comment by ikramsajal1980** [comment]
Configure https your problem will solve.
I got the same problem , solved after create Self-Signed SSL Certificate

**Comment by ikramsajal1980** [comment]
Configure https your problem will solve.
I got the same problem , solved after create Self-Signed SSL Certificate

**Comment by guifsdev** [comment]
I also have the same issue in 4.9.5deb2. It started happening deliberately in a table I'm working on that I could normally interact through mysql repl. Issue happens in both Firefox and Google Chrome. Changed `post_max_size` from 8M to 16M to no avail.
Unfortunately still can't find a solution and going back to DBeaver. 
OS: Ubuntu 20.04

**Comment by williamdes** [comment]
> I also have the same issue in 4.9.5deb2. It started happening deliberately in a table I'm working on that I could normally interact through mysql repl. Issue happens in both Firefox and Google Chrome. Changed `post_max_size` from 8M to 16M to no avail. Unfortunately still can't find a solution and going back to DBeaver. OS: Ubuntu 20.04

As you are using the Debian/Ubuntu version I would recommend you to try one of the following methods to update: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by sadeghipour** [comment]
it seems that https fixes this issue.

**Comment by alexissel** [comment]
I'm still having the issue after login...

- Operating system: AlmaLinux 9.2
- Web server: Apache 2.4.53
- Database version: MariaDB version 10.5.16
- PHP version: 8.0.20
- phpMyAdmin version: 5.2.0

Any solutions for this?

**Comment by williamdes** [comment]
> I'm still having the issue after login...

Try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)

**Comment by alexissel** [comment]
Just tried it and it doesn't work.

When `auth_type = cookie` the log in doesn't work and also not showing any error messages.
When `auth_type = http` the log in works but it shows the "connectivity to the server has been lost" message.

**Comment by williamdes** [comment]
> Just tried it and it doesn't work.
> 
> When `auth_type = cookie` the log in doesn't work and also not showing any error messages. When `auth_type = http` the log in works but it shows the "connectivity to the server has been lost" message.

Can you open a new issue so we discuss this?
I think you have a server misconfiguration

**Comment by alexissel** [comment]
Sure

**Comment by alexissel** [comment]
Here's the [new issue](https://github.com/phpmyadmin/phpmyadmin/issues/18049) @williamdes

**Comment by zag2me** [comment]
Just ran into this issue as well. Seems cloudflare default security rules breaks phpmyadmin currently.

Mysql 8 and PHP 7 (latest verisons)

<img width="989" alt="image" src="https://github.com/phpmyadmin/phpmyadmin/assets/1050512/9a8e0c1b-759c-482f-a68d-ae82cd48c1a5">

Just disabling those and my 403 error disappeared. 

Adding here as this is the first hit on google for the error message.

**Comment by williamdes** [comment]
Thanks for reporting this @zag2me
Can you open a new issue for us to have a look if this can be fixed in some way?

**Comment by williamdes** [comment]
> Also try changing memory_limit to -1 in php.ini file, then reload or restart your php.

Be cautious with this value, it can burst the server's memory. It's best to use a big value like `1G`

**Comment by sivehost** [comment]
Very true, rather use 1G if you do not know average sizes of your workloads.

**Comment by countachqv** [comment]
My solution:
Just split the sentence into two lines:

Example:
```
DELETE FROM files WHERE pathnamehash = '123ac502fa2e69767c724b4712075018a293eddf';
```

Gets the error: 

But:

```
DELETE
FROM mdl_files WHERE pathnamehash = '123ac502fa2e69767c724b4712075018a293eddf';
```
..works !

Don't ask me why...
