### ISSUE TITLE
Composer install v5.1 issue

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/phpmyadmin#16681]
I am installing a new version by command below:
`composer create-project phpmyadmin/phpmyadmin --no-dev`

But after install PHPMyAdmin is not working, I've checked the network tab in the browser and found many requests to resources in `js/dist` folder but this folder is empty.

I guess `js/src` folder has to be moved/renamed to `js/dist`.
Could you please check the composer script?

**Comment by williamdes** [comment]
Hi @Jay04653 
you need to run `yarn --production`  to compile the JS files but this should be fixed on the next run of the script

**Comment by Jay04653** [comment]
@williamdes, your solution is not working:
```
yarn --production
Usage: yarn [options]

yarn: error: no such option: --production
```

**Comment by williamdes** [comment]
```
yarn --production
yarn install v1.22.5
```

Maybe try `yarn install --production` or `yarn install`

You seem to be using a legacy version ?

**Comment by Jay04653** [comment]
I'm trying on 5.1.
Still not working but ok, I'll wait for a fix.

**Comment by williamdes** [comment]
Seems fixed: https://github.com/phpmyadmin/composer/commit/ff7174344fa2a4490ee2bc89344d286914e976b6
https://github.com/phpmyadmin/composer/tree/5.1.x/js/dist
