### ISSUE TITLE
phMyAdmin 5.5.1 & Xamp 8.1.2 > deprecation notices !

### ISSUE THREAD

**Issue by osworx** [phpmyadmin/phpmyadmin#17418]
Using the lastest XAMPP version with phpMyAdmin 5.5.1, I get "endless" **deprecation notices** at every and each action!
Not useable to work with.
My question is: how can I disable those output?

As it seems, 99% of all messages are related to **twig**.
Some samples:

```Deprecation Notice in .\vendor\twig\twig\src\Loader\FilesystemLoader.php#40
realpath(): Passing null to parameter #1 ($path) of type string is deprecated

Backtrace

FilesystemLoader.php#40: realpath(NULL)
Template.php#57: Twig\Loader\FilesystemLoader->__construct(string 'D:\\xampp\\phpMyAdmin\\\\templates\\')
Theme.php#101: PhpMyAdmin\Template->__construct()
Theme.php#174: PhpMyAdmin\Theme->__construct()
ThemeManager.php#307: PhpMyAdmin\Theme::load(
string './themes/metro',
string 'D:\\xampp\\phpMyAdmin\\./themes/metro/',
)
ThemeManager.php#79: PhpMyAdmin\ThemeManager->loadThemes()
ThemeManager.php#121: PhpMyAdmin\ThemeManager->__construct()
ThemeManager.php#385: PhpMyAdmin\ThemeManager::getInstance()
common.inc.php#240: PhpMyAdmin\ThemeManager::initializeTheme()
index.php#20: require_once(.\libraries\common.inc.php)
```

```
Deprecation Notice in .\vendor\twig\twig\src\Markup.php#35
Return type of Twig\Markup::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

ClassLoader.php#444: include(.\vendor\twig\twig\src\Markup.php)
ClassLoader.php#322: Composer\Autoload\includeFile(string 'D:\\xampp\\phpMyAdmin\\vendor\\composer/../twig/twig/src/Markup.php')
46f1bfbf4328d3d22fddffb9178fdeb9868d0740e4cc8b5bbd6f2fcfb8e4523e.php#59: Composer\Autoload\ClassLoader->loadClass(string 'Twig\\Markup')
Template.php#405: __TwigTemplate_034511bee5325c368ee003e3d97d6cb47c3e1c94ebb527bcf0b76ba7818d1ac6->doDisplay(
array,
array,
)
Template.php#378: Twig\Template->displayWithErrorHandling(
array,
array,
)
Template.php#390: Twig\Template->display(array)
TemplateWrapper.php#45: Twig\Template->render(
array,
array,
)
Template.php#132: Twig\TemplateWrapper->render(array)
Header.php#714: PhpMyAdmin\Template->render(
string 'javascript/variables',
array,
)
Header.php#193: PhpMyAdmin\Header->getVariablesForJavaScript()
Header.php#142: PhpMyAdmin\Header->addDefaultScripts()
Response.php#184: PhpMyAdmin\Header->__construct()
Response.php#215: PhpMyAdmin\Response->__construct()
common.inc.php#296: PhpMyAdmin\Response::getInstance()
index.php#20: require_once(.\libraries\common.inc.php)
```

And so on!
- Operating system: Win 11 Pro
- Web server: XAMPP
- Database version: 10.4.22-MariaDB
- PHP version: 8.1.2
- phpMyAdmin version: 5.1.1

- Browser: FF (latest), Chrome (latest)

I just want to know how do disable these messages.
Or will an update (if possible with XAMPP) to the latest release of phpMyAdmin solve these issues?

thanks in advance!

**Comment by ibennetch** [comment]
There were definitely a lot of these deprecation notices some time ago, but I just tried with phpMyAdmin 5.1.1 and PHP 8.1 and don't see any of them. I wonder if there's something going on with how XAMPP packages it. I suggest either using the latest phpMyAdmin (you can put it in a subdrectory of your web root, rather than replacing the XAMPP phpMyAdmin — which often causes problems) or checking with the XAMPP support folks for some assistance with it. I don't have much insight as to what could be going on in your specific situation but think one of those two options might be a decent solution for you.

**Comment by osworx** [comment]
@ibennetch 
Just tried the lasted version of phpMyAdmin from the releases page.
Now I am getting only this messages:
```
Deprecation Notice in .\libraries\classes\Util.php#1936
Function strftime() is deprecated

Backtrace

Header.php#582: PhpMyAdmin\Util::expandUserString(string '@HTTP_HOST@ / @VSERVER@ | @PHPMYADMIN@')
Response.php#380: PhpMyAdmin\Header->getPageTitle()
Response.php#505: PhpMyAdmin\Response->ajaxResponse()
PhpMyAdmin\Response->response()
```

Which is this here in the master:
https://github.com/phpmyadmin/phpmyadmin/blob/687a83923a7b0c5ce97eaf04d15645283b7b59e9/libraries/classes/Util.php#L1698

So still not fixed .. ?!
Only to use the @ to supress any output is not enough.

And inside the apache log this (don't know if from phpMyAdmin or XAMPP called):

```
script 'D:/xampp/phpMyAdmin/js/dist/messages.php' not found or unable to stat
```

**Comment by williamdes** [comment]
Please read #17249 as it seems that this user had the same issue only to realize that everything was fixed after a proper update. Also using XAMPP

**Comment by osworx** [comment]
@williamdes Thanks for answering.
Of course I have read all issues and pr here before I posted mine.

But compared to the other user, I did a complete new installation of phpmyadmin woth the latest official release from here.
And as written, using the @ to suppress any output at strftime(..) (see master and note before) cannot be the solution to be compatible with php 8.x
And I use php 8.1.2

btw: the "xampp support" must be sleeping somewhere, posted already a few days a message in the apachefriends forum .. till now no reponse!

**Comment by osworx** [comment]
Just to leave a feedbacl agter trying and working with different version ( 5.1.1 & 5.1.3).

Really don't know what's the reason for following (the XAMPP implemenation or the php 8.1.2 version phpMyAdmin is not compatible with).

5.1.3 is still not fully compatible with php 8.1.2, see message above.
There are a few more deprecated functions.

5.1.1is much worse, and it's a shame that XAMPP does not use the latest phpMyAdmin.

But both are not fully working as I know it since many years!
No setting to disable the output of messages, therefore the window is moving always up and down while generating the output.
The red window (saying something about errors and blablabla ..) is sometimes not reacting - click on it does nothing!
If in the left menu a table when hovering over an item, an eye is displayed - if that row is not wide enough, the whole screen jumps down.

Really don' t know who is responsible for final tests before publishing new releases, but that task has a lot of air and should be approved.

And the much worse of all those bad things, to be able to work now with the database, I had to install another tool for working with.
Maybe the things will be fixed somewhere in the future ..

**Comment by williamdes** [comment]
>Really don' t know who is responsible for final tests before publishing new releases, but that task has a lot of air and should be approved.

This is a rude statement, the team takes a lot if time revewing every change before releases
And releases are often tested before the release by the snapshot channel
Be sure we take this very seriously to provide high quality releases

That said you are free to contribute as I understand there is always place for improvement. 


> And the much worse of all those bad things, to be able to work now with the database, I had to install another tool for working with.
Maybe the things will be fixed somewhere in the future ..

I can assure you this is "fixed" in a backwards compatible way, maybe we can find out why you are still getting the errors
I tested and deployed phpmyadmin on so much servers and docker containers using PHP 8.1 now and wayyyy before PHP 8.1 was even released. As I said we take compatibility in a very serious way and try to be compatible a head of time, just read our changelogs and you will realise that. 

I understand the frustration about having to use another tool, we will listen to your reports and fix the issues if they are not already fixed for you to be able to use phpmyadmin back. 

All that said, we are not responsible for any bad php configuration done by XAMPP and I will try my best to reproduce this on a windows workstation. 

@osworx can you provide your php info output?

**Comment by osworx** [comment]
> > Really don' t know who is responsible for final tests before publishing new releases, but that task has a lot of air and should be approved.
> 
> This is a rude statement, the team takes a lot if time revewing every change before releases And releases are often tested before the release by the snapshot channel Be sure we take this very seriously to provide high quality releases

Yes, but that is my (own) feeling at the moment.
After using phpMyAdmin for a really long periode (more than 20 years) with several environements, this now is really too much for me.
I am developing websoftware, and time is money.
Therefore, after that long time I expected to get a full working and bug free release.

> I can assure you this is "fixed" in a backwards compatible way, maybe we can find out why you are still getting the errors I tested and deployed phpmyadmin on so much servers and docker containers using PHP 8.1 now and wayyyy before PHP 8.1 was even released. As I said we take compatibility in a very serious way and try to be compatible a head of time, just read our changelogs and you will realise that.
> 
> I understand the frustration about having to use another tool, we will listen to your reports and fix the issues if they are not already fixed for you to be able to use phpmyadmin back.
> 
> All that said, we are not responsible for any bad php configuration done by XAMPP and I will try my best to reproduce this on a windows workstation.
> 

As stated, I am using php 8.1.2 on a Win11 Pro PC.
Windows because of several reasons, while I am working also on some Linux stations.

> @osworx can you provide your php info output?

What exactly do you want to see (or have)?
Do you want to heave it here, or send it by email?

**Comment by liviuconcioiu** [comment]
@osworx if you don't need a specific phpMyAdmin version, or Apache, you can also get rid for XAMPP and install everything by yourself, PHP, phpMyAdmin, nginx, MySQL. I'm on Windows myself and everything works like a charm with the latest versions.

**Comment by williamdes** [comment]
> What exactly do you want to see (or have)?
Do you want to have it here, or send it by email?

The full output would really help, you can email me at williamdes [at] wdes.fr

> As stated, I am using php 8.1.2 on a Win11 Pro PC.
Windows because of several reasons, while I am working also on some Linux stations.

Would you mind sending here your full and precise version of XAMPP ?

> Yes, but that is my (own) feeling at the moment.
After using phpMyAdmin for a really long periode (more than 20 years) with several environements, this now is really too much for me.
I am developing websoftware, and time is money.
Therefore, after that long time I expected to get a full working and bug free release.

You know what, I also do developing websoftware, and my time is also money. But what I find unfair is that the money always goes in the pockets of companies and never/rarely to the people giving their free time to build software for people that "expected to get a full working and bug free release". To be clear, this is not a personal attack but just something I understood way before this issue was open ;)

> After using phpMyAdmin for a really long periode (more than 20 years) with several environements, this now is really too much for me.

This is something I understand. That said why did you report only one issue ?
See: https://github.com/phpmyadmin/phpmyadmin/issues/created_by/osworx

So, I/we am willing to provide you the most bug free release as possible. Let's find out where the issue is on your setup :)

But just have a look at the number of issues that where fixed in the two last 5.1 versions (5.1.1 and 5.1.2) it's crazy the amount of work that was done.

**Comment by williamdes** [comment]
This should now be fixed by #17734
I would advise you to try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know.
