### ISSUE TITLE
Wrong styles for add button from central columns on MariaDB

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17772]
### Describe the bug

With pmahomme theme, the add button from central columns on MariaDB has wrong styles.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/QA_5_2/index.php?route=/database/central-columns&db=mysql&server=1](https://demo.phpmyadmin.net/QA_5_2/index.php?route=/database/central-columns&db=mysql&server=1)
2. See error

### Expected behavior

The button background should be visible.

### Screenshots

https://user-images.githubusercontent.com/25424343/195249906-b1157e12-3a62-450a-8a2d-0428f245117e.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: 10.4.8-MariaDB-1:10.4.8+maria~stretch-log
- PHP version: 7.4.29
- phpMyAdmin version: 5.2.1-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Base branch for the fix: QA_5_2

**Comment by Arpit-Gulgulia** [comment]
Hi @williamdes, I would like to provide the fix on this issue as a part of the Hacktober fest, could you please assign this to me, or can I simply create PR for this?
Thanks!

**Comment by williamdes** [comment]
> Hi @williamdes, I would like to provide the fix on this issue as a part of the Hacktober fest, could you please assign this to me, or can I simply create PR for this? Thanks!

Sure, feel free to go ahead

**Comment by Arpit-Gulgulia** [comment]
Thanks for confirming!

@williamdes , is this expected or will it be fine?
![image](https://user-images.githubusercontent.com/48010798/195284673-fc759294-932e-4bde-b9f0-055ce2d1a686.png)

On hover Add button:
![image](https://user-images.githubusercontent.com/48010798/195285074-2fe1fd83-c587-448f-8051-f10e92726abe.png)

Please let me know if this looks fine, i will create PR.

**Comment by williamdes** [comment]
> Thanks for confirming!
> 
> @williamdes , is this expected or will it be fine? ![image](https://user-images.githubusercontent.com/48010798/195284673-fc759294-932e-4bde-b9f0-055ce2d1a686.png)
> 
> On hover Add button: ![image](https://user-images.githubusercontent.com/48010798/195285074-2fe1fd83-c587-448f-8051-f10e92726abe.png)
> 
> Please let me know if this looks fine, i will create PR.

It does not look like other buttons of the theme 🤔. Did you use some existing class?

**Comment by Arpit-Gulgulia** [comment]
No, the **td** element of this table was set to white background, and because of this the grey background for the table was overridden, and that's why there were two floating cubes we see at the bottom left corner and bottom right corner.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/48010798/195289991-804f39d6-8e7a-4c07-98d8-e94b3f8cc613.png">

So I removed the white background from the td element, so the grey background appears properly. 
The below screenshot will help what I'm trying to say:-
<img width="948" alt="image" src="https://user-images.githubusercontent.com/48010798/195290892-a75bc349-c2e0-418f-b6d0-cae932cfd85a.png">

Regarding Add button color, it is coming with the existing class only, i haven't added anything for it.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/48010798/195291632-b247532a-5080-4a1d-afad-0615c3bab6fe.png">

**Comment by williamdes** [comment]
Oh okay, if you have found an override for this particular case feel free to open a pull-request

**Comment by Arpit-Gulgulia** [comment]
Hi @williamdes, I see the demo site is now showing the correct styling for central columns on MariaDB. 
![image](https://user-images.githubusercontent.com/48010798/195482573-c0a85f86-334c-42e7-bcab-f8a222e5e938.png)

So could you please confirm if the still is being resolved by someone or can I create a PR for the same?
Thanks!

**Comment by williamdes** [comment]
> Hi @williamdes, I see the demo site is now showing the correct styling for central columns on MariaDB. ![image](https://user-images.githubusercontent.com/48010798/195482573-c0a85f86-334c-42e7-bcab-f8a222e5e938.png)
> 
> So could you please confirm if the still is being resolved by someone or can I create a PR for the same? Thanks!

Yes, its is still there. But you are not using the right form ;)
![image](https://user-images.githubusercontent.com/7784660/195959907-f925bdba-c0a0-43ae-83de-347aab5d6ab8.png)
You need to go to "Central columns" on a setup where phpMyAdmin configuration storage is enabled

**Comment by Arpit-Gulgulia** [comment]
I followed the steps and URL that @liviuconcioiu shared and I don't see the issue now demo site. Could you please share your steps? Thanks

**Comment by liviuconcioiu** [comment]
@Arpit-Gulgulia the issue is still there on the demo site.

https://user-images.githubusercontent.com/25424343/196324933-2f02dfbd-73d9-4a21-bf81-37ff47e60a8a.mp4

**Comment by Arpit-Gulgulia** [comment]
@liviuconcioiu , @williamdes fixed the issue. Please review the changes. Thanks!

![image](https://user-images.githubusercontent.com/48010798/196343733-90bf9643-db5e-4f92-8612-265cdcf7674a.png)

On hover:
![image](https://user-images.githubusercontent.com/48010798/196343841-0802adab-b202-492f-8421-e142d9fc7002.png)
