### ISSUE TITLE
Unable to create a view from tree view button

### ISSUE THREAD

**Issue by joomlahenk** [phpmyadmin/phpmyadmin#17944]
### Describe the bug

Maybe a bug or just a question how to solve:
Unable to create a view. I get no error or any other message. The loading... is displayed for 0.5 sec

### To Reproduce

1. Collapse views
2. Click on new

### Expected behavior

The box for creating a view is displayed

### Server configuration

I use the Official phpMyAdmin Docker image, running on a Synology system for a local site.

Database server:
Server: MariaDB Docker (192.168.178.23 via TCP/IP)
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.10.2-MariaDB-1:10.10.2+maria~ubu2204 - mariadb.org binary distribution
Protocol version: 10
User: root@172.17.0.1
Server charset: cp1252 West European (latin1)

Webserver:
Apache/2.4.53 (Debian)
Database client version: libmysql - mysqlnd 8.0.19
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 8.0.19

phpMyAdmin version: 5.2.0

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

### Additional context

I created many views in the past, but now I am unable to create one.
If I press view->new I get no error or any other message. Only loading... is displayed for 0.5 sec and then nothing happens.
It happens with all databases and mysql and mariadb servers. The databases are working well.
It looks like there is a limit or cache issue, but I could not find.

**Comment by williamdes** [comment]
Duplicate of #17390

**Comment by williamdes** [comment]
Can you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)? 

It should be fixed now

**Comment by joomlahenk** [comment]
Tried the latest 5.2 version in development (phpMyAdmin 5.2+snapshot). There are two versions in that image. The 5.2 snapshot gives the same issue, the 5.3 snapshot gives a warning "View name can not be empty". I click to dismiss and then still nothing happens.

**Comment by joomlahenk** [comment]
OK. Since this does not work, I changed back to PMA version 5.1.3 and now its working!
Maybe you need to reopen this issue, because it's not fixed.

**Comment by williamdes** [comment]
Oh, I will check this once more then

**Comment by williamdes** [comment]
I can confirm the bug, I have an idea of what it could be. Given that if you are on a table's result page the button works.

**Comment by eagle1978** [comment]
I suffered from the same issue in PhpMyAdmin 5.2
A normal browser refresh on even opening a new window or a new browser (Edge) did not work.
Somehome a hard refresh (Ctrl + Shift + R) did seem to resolve the issue

**Comment by williamdes** [comment]
> I suffered from the same issue in PhpMyAdmin 5.2 A normal browser refresh on even opening a new window or a new browser (Edge) did not work. Somehome a hard refresh (Ctrl + Shift + R) did seem to resolve the issue

Can you still reproduce this issue reliability in 5.2.1?

**Comment by eagle1978** [comment]
Hi @williamdes, sorry I am not in control of the PhpMyAdmin version.
I am able to work around the issue by continuously using hard browser refreshes in version 5.2.0

**Comment by williamdes** [comment]
> Hi @williamdes, sorry I am not in control of the PhpMyAdmin version. I am able to work around the issue by continuously using hard browser refreshes in version 5.2.0

That's good you found a workaround, can you let me know when you tried 5.2.1?

**Comment by eagle1978** [comment]
I will if that is the case. Unfortunately the use of this PhpMyAdmin environment is temporary (3-week assignment)
